### ISSUE TITLE
main.exe is reproduce but http server is not restart

### ISSUE THREAD

**Issue by chjiyun** [air-verse/air#106]
```
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "./tmp/main"
```
change the code and air watch the files successfully but http service is old

**Comment by chjiyun** [comment]
@xiantang  yes, terminal print
```
api\index.go has changed
building...
running...
```
but http server is not restart

**Comment by xiantang** [comment]
@chjiyun maybe old process not be killed..

**Comment by chjiyun** [comment]
@xiantang   I update the air and then the http server is running ok，but colorful log missed

**Comment by wandercn** [comment]
hotbuild.ffactory.org
