### ISSUE TITLE
Execute binary before build

### ISSUE THREAD

**Issue by ifuyivara** [air-verse/air#126]
Hello!

I was wondering if it's possible to execute the binary command before executing the build, this is specially helpful when running a service inside a container where you want the service to start right away and only rebuild when there is a change in the code.

Sort of similar to the `--start-service` flag in https://github.com/cespare/reflex#--start-service

**Comment by rizalgowandy** [comment]
Pretty sure, you could.
Just use a Makefile command and replace the cmd.

```
[build]
# Just plain old shell command. You could use `make` as well.
cmd = "make run-command-then-build"
```

Then inside your Makefile.
Create the `run-command-then-build`.
