### ISSUE TITLE
Colour of gin's log

### ISSUE THREAD

**Issue by liuzhaomax** [air-verse/air#128]
How can I remove ?[97;42m] and change it to color?
I have already used gin.DefaultWriter = colorable.NewColorableStdout()
Goland can show color on gin's log, but no color when the system is launched by air.

launched by air
![image](https://user-images.githubusercontent.com/20788414/100849120-344c6680-34d6-11eb-9fe1-e3e921bd8a9d.png)

launched by goland
![image](https://user-images.githubusercontent.com/20788414/100849868-1af7ea00-34d7-11eb-9897-679153831a45.png)

launched by .exe
![image](https://user-images.githubusercontent.com/20788414/100849959-3662f500-34d7-11eb-8527-7d1c3ebd51bd.png)

**Comment by liuzhaomax** [comment]
Windows

**Comment by birdycn** [comment]
me too

**Comment by birdycn** [comment]
how about now?

**Comment by birdycn** [comment]
hello

**Comment by birdycn** [comment]
Windows

The same issue occurs on gorm's log, too.

**Comment by birdycn** [comment]
how about now

**Comment by Shirtiny** [comment]
Windows，
me too

**Comment by Apostle-lemon** [comment]
The same occurs
