### ISSUE TITLE
execute custom commands before and after a file changes or globally

### ISSUE THREAD

**Issue by frederikhors** [air-verse/air#14]
Is there a way to execute custom commands before and after a file changes or globally?

For example: `yarn build` if `assets` folder content changes?

**Comment by cosmtrek** [comment]
I think you could use Makefile to finish this, just `make build` in `cmd`.

```Makefile
build:
    yarn build
    go build 
```

But now it does not support hooks around build or executing commands. Maybe it'll be implemented in the future.

**Comment by 0xquark** [comment]
Hi , I am working on a similar problem where i need to execute custom build commands for different files. Is this feature implemented yet ?
Also @frederikhors Can you tell me how you made your workaround for this problem ?

**Comment by andrioid** [comment]
The "before" can easily be solved with a little scripting, the _after_ is something I'm missing. I'm using [browser-sync](https://browsersync.io/docs/command-line) to reload the browser when the server reloads, and I need to do that _after_ the server loads.
