### ISSUE TITLE
How could I execute command after running executable file?

### ISSUE THREAD

**Issue by student-101** [air-verse/air#188]
I'm developing web application with [gin](https://github.com/gin-gonic/gin) and [realize](https://github.com/oxequa/realize).
I want to use air instead of realize, but I don't know how to execute command after server has started.

I tried to use Makefile, but it failed because next command is waiting for server stopping.

**Comment by SuzurikawaChihiro** [comment]
@student-101 
日本人でしたので日本語で書きますね
この質問はローカルのDocker環境でairの動かし方が分からないと言うことですか？

そう言うことでしたら、こちらの記事のDockerfileを真似てやってみてください👍
https://blog.zuckey17.org/entry/golang-gin-air

**Comment by student-101** [comment]
@SuzurikawaChihiro 
返信ありがとうございます。
同じホットリロードライブラリのrealizeではafterというパラメータを指定でき、それと同じ機能がairにないかと探していました。
それを指定すると、リビルド＆実行が終わった後に処理を挟み込めます。
