### ISSUE TITLE
Why do I keep receiving this error for hot reloads inside contianers ? 

### ISSUE THREAD

**Issue by knightswatch3** [air-verse/air#232]
/bin/sh: /home/go-component/tmp/main: Text file busy

I understand what the error means but isn't it what AIR should be supposed to help me out with ?

How do I get rid of these errors ?

**Comment by adamgotterer** [comment]
I'm having the same issue inside docker

**Comment by nwadams** [comment]
@palakoti0312 @adamgotterer do you see this error as being related to having multiple builds happening concurrently and multiple processes starting? https://github.com/cosmtrek/air/issues/216#issuecomment-1027245136

**Comment by adamgotterer** [comment]
I'm really not positive what the issue is. My gut says it's some sort of file contention issue where the OS, Air, or Docker isn't freeing up access fast enough. But I haven't had a chance to dig in any deeper since I filed this ticket.
