### ISSUE TITLE
/bin/sh: No such file or directory

### ISSUE THREAD

**Issue by definev** [air-verse/air#262]
I installs air with `go install` command.
I'm already add `export PATH=$PATH:$(go env GOPATH)/bin` in my `.zshrc` file.
My device is M1 chip.

<img width="860" alt="Screen Shot 2022-03-21 at 17 59 54" src="https://user-images.githubusercontent.com/62325868/159248131-9e1bb537-14ef-4362-a48f-435d3c1e0393.png">

**Comment by xiantang** [comment]
could u provide your air config file?

**Comment by iamhabbeboy** [comment]
@xiantang
Here's mine, the server is in the server/ directory 

```
root = "./server" 
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/main ./server/main.go"
# Binary file yields from `cmd`.
bin = "./tmp/main"

# Customize binary.
# This is how you start to run your application. Since my application will works like CLI, so to run it, like to make a CLI call.
# full_bin = "./tmp/main http"
# This log file places in your tmp_dir.
log = "air_errors.log"
# Watch these filename extensions.
include_ext = ["go", "yml"]
include_dir = ["server"]
# Ignore these filename extensions or directories.
exclude_dir = ["tmp"]
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms

[log]
# Show log time
time = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
```

**Comment by AbenezerKb** [comment]
I was facing the same problem, it worked when I removed the ```.``` from ```bin = "./tmp/main" ``` . so it should be like this ```bin = "/tmp/main" ```

**Comment by petersrule** [comment]
I have the same issue and the path it gives is "/bin/sh: /Users/name/Documents/Documents: No such file or directory" where I have no Documents folder in the Documents folder so of course it finds nothing. Why is it looking there? What is it looking for and how do I change where it is looking?

I am on a Mac too but the intel ones. I Abenezer's suggestion but that didn't fix the problem.
