### ISSUE TITLE
feature-request：About the signal when the killCmd method is executed

### ISSUE THREAD

**Issue by woshizilong** [air-verse/air#29]
🎉Thank you for your air, I like it very much.

I use Gin to write code for the server.
When the server will be shut down，I need to do some processing like closing the database connection.
But because the killCmd method sent the syscall.SIGKILL signal, there is no time to close the database connection.
When my Gin server is started again by air, an error can occur because the database connection is not closed properly and the server cannot be started.
Can I configure the semaphore in config so that I can pass syscall.SIGTERM.
It is better if air can set a timeout for waiting for the kill command to end.

This is just a suggestion, I hope to improve the air this useful tool.

**Comment by cosmtrek** [comment]
I think it's better you handle the syscall.SIGKILL signal in your programs. Please refer to [this article](https://stackoverflow.com/questions/11268943/is-it-possible-to-capture-a-ctrlc-signal-and-run-a-cleanup-function-in-a-defe).

**Comment by woshizilong** [comment]
I tried to handle syscall.SIGKILL and the air started before I closed the connection.

**Comment by cosmtrek** [comment]
I'll try it.

**Comment by hisato-eguchi** [comment]
thank you for air!!

i tried to handle syscall.SIGKILL in my program.

```
sig := make(chan os.Signal)
signal.Notify(sig, syscall.SIGKILL)
<- sig
log.Print("received sigkill")
```

but, i couldn't received SIGKILL.

so, it's better if i could pass SIGTERM.

**Comment by hisato-eguchi** [comment]
thank you for air!

i tried this code in my program.

```
sig := make(chan os.Signal)
signal.Notify(sig, syscall.SIGKILL)
<- sig
log.Print("received SIGKILL")
```

but, i couldn't receive SIGKILL.

i hope i can send SIGTERM instead of SIGKILL.
