### ISSUE TITLE
Air load on mac, cannot be accessed by others.

### ISSUE THREAD

**Issue by Lilihx** [air-verse/air#311]
Air load a server on port, eg 8080. Cannot be accessed by others.
Instead, using " go run main.go" to start the server, it can be accessed.

I found that, it will **pop up a "net work confirm"** after "go run main.go"
While using air, it didnot happened.

My mac os is 12.4 version.

**Comment by devashishRaj** [comment]
you remember the fix for this ?

**Comment by Lilihx** [comment]
I didnot fix this ...

**Comment by devashishRaj** [comment]
it probably haas nothing to do with air as if i use "go run main.go" , the program will ask of network permission but not if i use run executable file produced from "go build main.go" , which is default build command in toml file , so i think it's an issue of editing go.mod to include local packages during build. i'll try on weekend to do this.
