### ISSUE TITLE
Process not killed when closing terminal window/tab/session

### ISSUE THREAD

**Issue by bobmoff** [air-verse/air#377]
I am using iTerm on Mac and when closing the view/window that is running Air, the process is still running when I look at "Activity monitor".

Very easy reproduced. Just init a project with following code:

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	// print hello world with an 1 second interval, for ever
	for {
		fmt.Println("Hello World")
		time.Sleep(time.Second)
	}
}
```

**Comment by AJ-Brown-InTech** [comment]
I have come across this problem as well  about a week ago and ran your code above, it's hard to reproduce because its closing properly for me but i do remember this problem, can you re verify and what shell are you using?

**Comment by bobmoff** [comment]
It happens for me every time I try.

i am using zsh on macOS.

**Comment by alankritjoshi** [comment]
Same issue here. 

I think it has something to do with the fact that terminals typically send SIGHUP instead of SIGTERM when killing the panes.

My assumption is that air isn't honouring SIGHUPs gracefully, which leads to zombie processes.

**Comment by cosmtrek** [comment]
@bobmoff I can't reproduce it using Terminal on macOS... Could you try it?

**Comment by bobmoff** [comment]
The issue seems to be fixed. This is great!
