### ISSUE TITLE
unable to watch files with docker compose on windows host

### ISSUE THREAD

**Issue by Merith-TK** [air-verse/air#403]
I use `cosmtrek/air` docker container because I am developing an program that utilizes Go Plugins, which do not work on an windows host, this allows me to test and develop them

https://gitlab.com/Merith-TK/ultron-control < my project

When i run it, it builds and does everything as one expects, however when I alter a file, it does not catch it in the container and therefore, does not reload

**Comment by Merith-TK** [comment]
![image](https://user-images.githubusercontent.com/10422110/229198437-2c178921-76cf-4e9e-9f03-722467468af1.png)
`Docker version 20.10.23, build 7155243`

**Comment by a0v0** [comment]
Same here. I am on windows 11.

**Comment by a0v0** [comment]
If using wsl, put your code in wsl file system and open the project from there.
