### ISSUE TITLE
Please support absolute paths other than the root directory

### ISSUE THREAD

**Issue by chenyu1990** [air-verse/air#41]
configs:
```
root = "/data/project"
# Optional! If `watch_dir` is empty, use `root`.
watch_dir = ""
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./cmd/server/server ./cmd/server"
# Binary file yields from `cmd`.
bin = "./cmd/server/server"
# Customize binary.
full_bin = "./cmd/server/server -c ./configs/config.toml -m ./configs/model.conf"
```

errors:
```
can't load package: package ./cmd/server: cannot find package "." in:
        /root/cmd/server
```

**Comment by cosmtrek** [comment]
What's your project structure?

**Comment by MaMrEzO** [comment]
I want same thing, I am developing a module and a project at same time,
So whenever I made a change in module(Outside root directory) I should make a change to project too(an empty line add or remove) to see how changes will effect.
For more info, in my case, both module and project are in same directory:
```
GO/../mamrezo/myModule
GO/../mamrezo/myProject
```
I cant move the module to the project folder, the module itself been used by other projects too.
