### ISSUE TITLE
希望可以增加配置文件变更，也可以 reload 

### ISSUE THREAD

**Issue by edocevol** [air-verse/air#507]
为了表达和理解无误，用中文了。

服务的各种 yaml、toml 配置发生变更但代码本身无变更时，也可以reload。
```toml
include_ext = ["go", "yaml", "yml", "mod", "sum"]
```

**Comment by cosmtrek** [comment]
Duplicated https://github.com/air-verse/air/issues/465, plan to finish this 😄
