### ISSUE TITLE
Inconsistent Install Recommendations in English and Chinese READMEs

### ISSUE THREAD

**Issue by eMUQI** [air-verse/air#596]
Hi,

I noticed that the English README recommends using `go install`, while the Chinese README recommends `install.sh`. Both READMEs cover all installation methods, but the recommended methods are different, which can be confusing.

Is this because the Chinese README hasn't been updated? I'm happy to help update it to keep everything consistent.

Thanks!

**Comment by xiantang** [comment]
Yes, Chinese version README has'nt been updated. PR is welcome
