### ISSUE TITLE
Returning HTML breaks proxy

### ISSUE THREAD

**Issue by mattbrandman** [air-verse/air#615]
It appears that when returning HTML from an endpoint the proxy seems to intercept and not return the traffic to the site. You can reproduce by making a simple endpoint that returns ```<div></div>``` and see that it is not in the payload. Returning plaintext or json does not suffer from this issue. Noticed this issue as I'm working with HTMX responses and they do not seem to work from the proxy but work from the non-proxy port.

**Comment by michaelgaultjr** [comment]
I'm also experiencing this issue. Would be nice to get a fix for this soon, really would be nice to have hot reloading while working with Go And HTML.

**Comment by diego-velez** [comment]
+1

**Comment by ndajr** [comment]
This should be fixed, please download the new air version. Make sure you have a <body></body> tag in your html page

**Comment by mattbrandman** [comment]
Can confirm this is fixed in 1.52.3! Thank you incredible experience using this now!
