### ISSUE TITLE
"air -c" and "air init" can`t run

### ISSUE THREAD

**Issue by Strke** [air-verse/air#623]
When I use this command `air init` on linux, and I get error `init: required argument missing.`

and `air -c .air.toml` get error  `-c:command not found`

Hope to find a solution, thank you！

**Comment by Strke** [comment]
my `.bashrc` like this
```
export GOROOT=/usr/local/go
export GOPATH=/home/gpo/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export PATH=$PATH:$(go env GOPATH)/bin
alias air=`$(go env GOPATH)/bin/air`
```

**Comment by xiantang** [comment]
could u run `air -v`?

**Comment by Strke** [comment]
Thanks for your reply, I solved it.
In the `.bashrc`
```
alias air=$(go env GOPATH)/bin/air
```
