### ISSUE TITLE
Not exexuting the executable

### ISSUE THREAD

**Issue by Top-g-hash** [air-verse/air#630]
__    _   ___  
 / /\  | | | |_) 
/_/--\ |_| |_| \_ v1.52.3, built with Go go1.22.4

watching cmd
watching cmd/class-examples
watching cmd/class-examples/blocks
watching cmd/tmp
!exclude css
!exclude images
!exclude tmp
watching views
building...
running...
/bin/sh: line 1: /home/atharva-pc/Documents/10: No such file or directory

im tires of searching more its been 5-6hours plz help
i chagpted and got htat the air is not able to find the executable 
when i manually build and exec it works fine

**Comment by Top-g-hash** [comment]
Solved
Air was not able to detect my directory bcz I had spaced name 
My file was located in 10 projects with space in between
So changed it to 10-projects
/bin/sh: line 1: /home/atharva-pc/Documents/10:

**Comment by SahilDhingraa** [comment]
can you share the fix?

**Comment by Top-g-hash** [comment]
check ur path in which ur file is located if the path has any spacers in between as air stops reading  at the space
FOR EXAMPLE:
~/Documents/my projects/goproject (notice the space )
 this directory would be read till FOR as a space occurs it will stop reading

**Comment by SahilDhingraa** [comment]
I know that but is there any permanent solution to it so that path works with spaces also?

**Comment by Top-g-hash** [comment]
thats an interesting question i think this can reported as bug of somesort!!!

**Comment by huyho-vuatho** [comment]
> Solved Air was not able to detect my directory bcz I had spaced name My file was located in 10 projects with space in between So changed it to 10-projects /bin/sh: line 1: /home/atharva-pc/Documents/10:

God bless, you saved my day 🥰. I got the same problem with you. It seems an awkward but took me an hour to find a solution 😁
