### ISSUE TITLE
Why must rebuild when changed?

### ISSUE THREAD

**Issue by uiosun** [air-verse/air#632]
Hi, how to set "go run main.go" to air.
﻿
Why we must use "build & run"? when I has more function and file's project, the rebuild time will slow?

**Comment by michalb-goflink** [comment]
I did:

```toml
  cmd = "true"
  full_bin = "make run"
```

- `cmd` kind of needs to succeed, so let's fake a build.
- while `full_bin` runs `make run` which can be anything, for example `go run main.go`

> `full_bin` -  Customize binary, can setup environment variables when run your app.

**Comment by uiosun** [comment]
@michalb-goflink Cool bro! Very grateful to your work.

When night i will try to it, I hope it works for me.

**Comment by michalb-goflink** [comment]
The only downside I found is that `full_bin` command does not seem to be gracefully terminated. But that is no real issue in my code
