### ISSUE TITLE
Go 1.23 support

### ISSUE THREAD

**Issue by fschmtt** [air-verse/air#647]
Hey 😄 We recently upgraded our project to 1.23 and now cannot use the [cosmtrek/air](https://hub.docker.com/r/cosmtrek/air) image (built on 1.22) any more.

Do you plan to publish a 1.23 based Docker image any time soon?

I found this PR to do exactly that, which has been closed, though: https://github.com/air-verse/air/pull/638

**Comment by cosmtrek** [comment]
Yes, I'll upgrade the go version soon

**Comment by cosmtrek** [comment]
https://github.com/air-verse/air/pull/650

**Comment by fschmtt** [comment]
Thank your resolving this so quickly! 🚀
