### ISSUE TITLE
air can't run on windows11

### ISSUE THREAD

**Issue by ucdo** [air-verse/air#663]
go version:1.23.2

I ran `air` on command line,but gave me error:
![image](https://github.com/user-attachments/assets/b9a2348e-c194-49ad-829a-acf39c40431e)

I think It's the `'` and '\\' stop the command.

- [ ] `'\"F:\\Core2\\tmp\\main.exe\"'` 
- [x] `"F:\\Core2\\tmp\\main.exe"`

only `"F:\xxx\tmp\main.exe"` can run.

**Comment by oh0123** [comment]
same issue

**Comment by oh0123** [comment]
try set follow config in .air.toml
` full_bin = ".\\tmp\\main.exe"`

**Comment by ucdo** [comment]
> try set follow config in .air.toml ` full_bin = ".\\tmp\\main.exe"`

Thanks.It can work now.
