### ISSUE TITLE
Air Build Failure with Go 1.23.4

### ISSUE THREAD

**Issue by high-horse** [air-verse/air#712]
### Environment Details
- Air Version: v1.61.1
- Go Version: go1.23.4 linux/amd64
- Operating System: Linux

### Detailed Description
When running `air` in a Go project, it fails to build with the error:

no Go files in /home/camle/Desktop/extra/go/login-reg
failed to build, error: exit status 1

### Project Structure

.
├── cmd
│   └── main.go
├── http
│   ├── handlers
│   │   └── user_handler
│   │       ├── user_handler.go
│   │       └── user_model.go
│   ├── helper
│   │   ├── cookie.go
│   │   ├── jwt.go
│   │   ├── password.go
│   │   └── request_validator.go
│   ├── middleware
│   │   └── auth
│   │       └── auth.go
│   ├── response
│   │   └── response.go
│   └── router
│       └── router.go
├── initialize
│   └── database.go
├── go.mod
└── air.toml

### Reproduction Steps
1. Install Air
2. Navigate to project root
3. Run `air`

### Expected Behavior
Air should build and run the Go project

### Actual Behavior
Air fails to build, claiming no Go files exist

### Additional Information
- Manual `go build ./cmd/main.go` works correctly
- All Go files have correct `.go` extension
- Go module is correctly configured
- No obvious issues with project structure

### Diagnostic Information
- Confirmed Go files exist and are readable
- Project builds manually without issues
- Air version shows as v1.61.1

this is the error log:
``` bash

camle@camel:~/Desktop/extra/go/login-reg$ air

  __    _   ___
 / /\  | | | |_)
/_/--\ |_| |_| \_ v1.61.1, built with Go go1.23.4

mkdir /home/camle/Desktop/extra/go/login-reg/tmp
watching .
watching cmd
watching http
watching http/handlers
watching http/handlers/user_handler
watching http/helper
watching http/middleware
watching http/middleware/auth
watching http/response
watching http/router
watching initialize
watching sqlc
watching sqlc/database
watching sqlc/queries
watching sqlc/schema
!exclude tmp
building...
no Go files in /home/camle/Desktop/extra/go/login-reg
failed to build, error: exit status 1
running...
/bin/sh: 1: /home/camle/Desktop/extra/go/login-reg/tmp/main: not found
Process Exit with Code: 127
```

## this is air.toml content

```bash
root = "."
tmp_dir = "tmp"

# Verbose build command
build_cmd = "go build -v -o ./tmp/main ./cmd/main.go"
run_cmd = "./tmp/main"

[build]
# Explicitly list Go files and build settings
cmd = "go build -v -o ./tmp/main ./cmd/main.go"
include_ext = ["go", "env", "mod"]
include_dir = [
    "cmd", 
    "http", 
    "initialize", 
    "sqlc"
]
exclude_dir = [
    "tmp",
    ".git"
]

[log]
time = true
colors = true
level = "debug"
```

**Comment by istyf** [comment]
The default name for the config file has a leading dot (.air.toml). When air starts it does not find your config file, causing it to revert to defaults.

Rename the file to .air.toml or start air with the arguments -c air.toml

**Comment by high-horse** [comment]
Thank you so much for your help! It worked perfectly. I was banging my head for hours trying to figure out why it wasn’t working. This is my first time working with air, and I really appreciate the support!
