### ISSUE TITLE
Air won't see .air.toml 1.61.4

### ISSUE THREAD

**Issue by dima1034** [air-verse/air#721]
Air doesn't load the .air.toml configuration file in the latest release. After updating, running air -c .air.toml no longer reads the file. Steps to reproduce:

Build the Docker image using the provided Dockerfile (golang:1.23 for build, golang:1.23-alpine for runtime).
Run the container with air -c .air.toml.
Observe that air doesn't pick up .air.toml.
Expected behavior: air should correctly read and apply .air.toml.

**Comment by xiantang** [comment]
https://github.com/air-verse/air/pull/719
